common:
	@make -f makefile all

Exe=../../bin/luavm

Src_C=main.C \
	luavm.C \
	luamgr.C \
	wedge.C \
	suger.C \
	../common/logout.C

MY_FLAGS = ../../bin/lua.dll

include ../common/makefile.incl